### ISSUE TITLE
kubectl-frisbee command

### ISSUE THREAD

**Issue by kdamaski** [CARV-ICS-FORTH/frisbee#325]
## description
kubectl-frisbee command doesn't see the configuration file  used to connect to the server (/var/snap/microk8s/3883/credentials/client.config). I think that's the reason  for : 
![image](https://user-images.githubusercontent.com/64901487/192527406-94c1259a-49a4-4843-997c-d7f470f89302.png)

**Comment by fnikolai** [comment]
This is because the ~/.kube/config is missing.

If you use microk8s, run `microk8s config > ~/.kube/config".

I 've added instructions in the README.md

**Comment by kdamaski** [comment]
> This is because the ~/.kube/config is missing.
> 
> If you use microk8s, run `microk8s config > ~/.kube/config".
> 
> I 've added instructions in the README.md

Obstacle passed! A new one appeared  with the same command though :

![image](https://user-images.githubusercontent.com/64901487/193585039-d9d6a9c5-cd02-475f-a32e-02e659d9dd75.png)
